- name: Find enabled nginx site configs
  ansible.builtin.find:
    paths: /etc/nginx/sites-enabled
    file_type: any
  register: nginx_enabled_sites

- name: Remove unmanaged enabled site configs
  ansible.builtin.file:
    path: "{{ enabled_site.path }}"
    state: absent
  loop: "{{ nginx_enabled_sites.files }}"
  loop_control:
    loop_var: enabled_site
  when:
    - nginx_remove_unmanaged_sites
    - enabled_site.path | basename not in nginx_sites | map(attribute='name') | list
  notify: Reload Nginx

- name: Find available nginx site configs
  ansible.builtin.find:
    paths: /etc/nginx/sites-available
    file_type: file
  register: nginx_available_sites

- name: Remove unmanaged available site configs
  ansible.builtin.file:
    path: "{{ available_site.path }}"
    state: absent
  loop: "{{ nginx_available_sites.files }}"
  loop_control:
    loop_var: available_site
  when:
    - nginx_remove_unmanaged_sites
    - available_site.path | basename not in nginx_sites | map(attribute='name') | list
  notify: Reload Nginx
