[containers]
ansible-node1 ansible_connection=containers.podman.podman
ansible-node2 ansible_connection=containers.podman.podman

[firewalls]
firewall-node1 ansible_connection=containers.podman.podman
firewall-node2 ansible_connection=containers.podman.podman